apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: cnrprod1725782375-team-77723
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: flask-api
